security:
    password_hashers:
        App\Entity\Utilisateur: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: /login_check
                enable_csrf: true

            logout:
                path: app_logout
                target: app_home

    access_control: []
