security:
    # 1. HACHAGE DES MOTS DE PASSE
    password_hashers:
        App\Entity\Utilisateur: 'auto'

    # 2. COMMENT TROUVER LES UTILISATEURS (Le Provider)
    providers:
        # On dit à Symfony de chercher dans l'entité Utilisateur via la colonne 'email'
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    # 3. LES PARE-FEUX (Firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            provider: app_user_provider

            # On active l'authentificateur classique (Celui que notre contrôleur appelle !)
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

            # On active la déconnexion
            logout:
                path: app_logout
                # Où aller après la déconnexion ? Retour à l'accueil
                target: app_home

    # 4. CONTRÔLE D'ACCÈS (L'équivalent de vos "if" pour protéger les pages)
    access_control:
        # Décommentez (enlevez le #) pour protéger vos futures pages !
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        # - { path: ^/chef-projet, roles: ROLE_CHEF_PROJET }