when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect: true
            collect_serializer_data: false

when@test:
    framework:
        profiler: { collect: false }
